version: '3'

services:
  rest-api:
    build: ./backend/go-rest-api
    ports:
      - "8081:8081"
    networks: 
      - fullstack
  app:
    build: ./app
    ports:
      - "8080:8080"
    networks: 
      - fullstack
networks: 
  fullstack:
    driver: bridge
    
    
  